### ISSUE TITLE
custom.kvm.net.discover fails

### ISSUE THREAD

**Issue by thirstycat** [bushvin/zabbix-kvm-res#1]
running on Centos6.4 (python 2.6.6)

zabbix-kvm-res.py --resource net --action list fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-kvm-res.py", line 157, in <module>
    main()
  File "/usr/local/bin/zabbix-kvm-res.py", line 26, in main
    r = net_list(options)
  File "/usr/local/bin/zabbix-kvm-res.py", line 60, in net_list
    for net in conn.listAllNetworks():
TypeError: listAllNetworks() takes exactly 2 arguments (1 given)
```

**Comment by bushvin** [comment]
Which version of libvirt-python do you have?

[root@kvmhost ~]# rpm -q libvirt-python
libvirt-python-1.1.3.8-1.fc20.x86_64
[root@kvmhost ~]#

**Comment by thirstycat** [comment]
apparently a waaaay too old one:

rpm -q libvirt-python
libvirt-python-0.10.2-18.el6_4.15.x86_64

interestingly, I found that if I modify the net_list function:

```
def net_list(options):
  conn = kvm_connect()
  r = []
  for net in conn.listAllNetworks(63):
    r.append('\t\t{"{#NETNAME}":"'+net.name()+'"}')
  return '{ \n\t"data":[\n' +",\n".join(r) +'] \n}'
```

it works correctly.   I did a little digging in http://libvirt.org/html/libvirt-libvirt-network.html#virConnectListAllNetworksFlags to figure out what to pass it in terms of flags.

Same workaround for domain_list and pool_list as well.   I'm guessing later versions of libvirt-python just set a default flag value if none is supplied?

**Comment by bushvin** [comment]
I'll check it out in the morning and commit something a little more compatible with 'waaaaaayyyy old' versions ;)

**Comment by bushvin** [comment]
I wasn't able to find anything usefull about the value for the 'flag', but the default in libvirt-python-1.1.3.8 is 0, so I used this.
Could you give it a go?

**Comment by thirstycat** [comment]
Yup... using '0' works.  As does the '63' that I had tried yesterday.  Based on:

```
virConnectListAllNetworksFlags
enum virConnectListAllNetworksFlags {
VIR_CONNECT_LIST_NETWORKS_INACTIVE  =   1
VIR_CONNECT_LIST_NETWORKS_ACTIVE    =   2
VIR_CONNECT_LIST_NETWORKS_PERSISTENT    =   4
VIR_CONNECT_LIST_NETWORKS_TRANSIENT =   8
VIR_CONNECT_LIST_NETWORKS_AUTOSTART =   16
VIR_CONNECT_LIST_NETWORKS_NO_AUTOSTART  =   32
}
```

I figured 1+2+4+8+16+32 would give me all networks (or domains or pools).  Looks like 0 does the same and looks a bit cleaner :)
Anyway, aside from having to figure out this little piece, the script/template work great.  Thanks!

**Comment by bushvin** [comment]
I'm glad this got sorted. Thanks you for testing.
