### ISSUE TITLE
issue with latest data

### ISSUE THREAD

**Issue by Bsivamani** [bushvin/zabbix-kvm-res#12]
hi ,

I  have a Zabbix sever on centos 8 .

my kvm host is ubuntu 18.04.

keenly took the steps and i cant see latest data in the host.
i get the below error on items-Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "sh: 1: /usr/local/bin/zabbix-libvirt-res.py: not found"

i did change the chmod 777 on the python file in usr/local/bin in the kvm host server.

can you pls help me here.

**Comment by bushvin** [comment]
1. Never ever make a file 777... anybody could change the file and have it then executed by eg root. Better to `chmod 755`
2. Are you sure you have pulled the last version?
2. There's not a lot of info for me to go by. Please provide more logging. The entire python error message would be great.

**Comment by bushvin** [comment]
can you also post the output of
```bash
/usr/local/bin/zabbix-libvirt-res.py --resource pool --action list
/usr/local/bin/zabbix-libvirt-res.py --resource net --action list
/usr/local/bin/zabbix-libvirt-res.py --resource domain --action list
/usr/local/bin/zabbix-libvirt-res.py --resource host --action version
/usr/local/bin/zabbix-libvirt-res.py --resource host --action type
/usr/local/bin/zabbix-libvirt-res.py --resource net --action count_active
/usr/local/bin/zabbix-libvirt-res.py --resource net --action count_inactive
/usr/local/bin/zabbix-libvirt-res.py --resource domain --action count_active
/usr/local/bin/zabbix-libvirt-res.py --resource domain --action count_inactive
/usr/local/bin/zabbix-libvirt-res.py --resource pool --action count_active
/usr/local/bin/zabbix-libvirt-res.py --resource pool --action count_inactive
```

**Comment by bushvin** [comment]
wait a minute...
The script needs to be installed on your KVM server, not your Zabbix server
are you sure it is installed in /usr/local/bin ?

**Comment by Bsivamani** [comment]
hi yes , i have installed it on KVM host only.Let me grab those outputs for u.

cd /usr/local/bin/
balaji@ubuntuVm:/usr/local/bin$ ls
zabbix-libvirt-res.py
balaji@ubuntuVm:/usr/local/bin$

balaji@ubuntuVm:/usr/local/bin$ /usr/local/bin/zabbix-libvirt-res.py --resource pool --action list
-bash: /usr/local/bin/zabbix-libvirt-res.py: /bin/env: bad interpreter: No such file or directory

**Comment by Bsivamani** [comment]
And i have no selinux in the machine. so skipped those selinux steps.

these commands are not running;
balaji@ubuntuVm:~$ /usr/local/bin/zabbix-libvirt-res.py --resource pool --action list
-bash: /usr/local/bin/zabbix-libvirt-res.py: /bin/env: bad interpreter: No such file or directory

**Comment by Bsivamani** [comment]
may be im thinking my python is not working properly

**Comment by bushvin** [comment]
No it's not your python which is wrong.
It's the path to `env` which is not compatible with Ubuntu 18.04

check if you have `/usr/bin/env`
if so, you need to change the first line of the script:
```sh
#!/bin/env python
```
to 
```sh
#!/usr/bin/env python
```

**Comment by Bsivamani** [comment]
alaji@ubuntuVm:~$ python -V
Python 2.7.17

**Comment by Bsivamani** [comment]
> No it's not your python which is wrong.
> It's the path to `env` which is not compatible with Ubuntu 18.04
> 
> check if you have `/usr/bin/env`
> if so, you need to change the first line of the script:
> 
> ```shell
> #!/bin/env python
> ```
> 
> to
> 
> ```shell
> #!/usr/bin/env python
> ```

there is no such path as /usr/bin/env

**Comment by Bsivamani** [comment]
there is no such path as /usr/bin/env

**Comment by Bsivamani** [comment]
and these vms are in azure fyi

**Comment by bushvin** [comment]
You have kvm running on azure? Doesn't that kind of defeat the purpose?

But anyway...
The shebang defines which interpreter needs to be used to execute the script.
you could replace it with the python binary, eg `/usr/bin/python` if that is the full path to your python binary

So
```sh
#!/bin/env python
```
to
```sh
#!/usr/bin/python
```

**Comment by Bsivamani** [comment]
ya i did still the same
balaji@ubuntuVm:~$ #!/usr/bin/python
balaji@ubuntuVm:~$ /usr/local/bin/zabbix-libvirt-res.py --resource pool --action list
-bash: /usr/local/bin/zabbix-libvirt-res.py: /bin/env: bad interpreter: No such file or directory

Im using azure just for the testing purpose--

**Comment by bushvin** [comment]
This
`/bin/env: bad interpreter: No such file or directory`
means the shebang still points to /bin/env.

**Comment by Bsivamani** [comment]
> This
> `/bin/env: bad interpreter: No such file or directory`
> means the shebang still points to /bin/env.

ya im not able to edit the file - can you help how to do that

**Comment by bushvin** [comment]
No

**Comment by Bsivamani** [comment]
atlast i succeeded thanks for the help, it was using python 3 ,so i had change everything to python3

**Comment by vot4anto** [comment]
Have the same issue on KVM bionic, solved using #!/usr/bin/env python

Is not a way to be Linux flavor indipendent?
