### ISSUE TITLE
How and where do i monitor my KVM resource usage using this template

### ISSUE THREAD

**Issue by chamambom** [bushvin/zabbix-kvm-res#4]
I have followed the instructions and managed to install the template but i cant seem to make head and tail of where i should see the kvm resource usage

**Comment by bushvin** [comment]
Hi,
The template is called libvirt.
You can add it to a host when configuring the host:

Configuration >> Hosts
click host to which you want to add the libvirt template
click the "Template" tab
click "Add"
Change the filter in the new popup to show libvirt
check the "libvirt" template & press select
Save your host configuration.

The discovery process takes a while before it actually starts registering everything. Check the template for exact timings, but after an hour you should already start getting something.

I suggest you read this book if you want to learn more about zabbix: https://www.packtpub.com/networking-and-servers/zabbix-cookbook. It's a pretty good book.

**Comment by linkt** [comment]
hello,i use your template to the kvm resource usage,I find that the items is 0

![image](https://cloud.githubusercontent.com/assets/7455401/12444547/8875d07c-bf9a-11e5-8d9c-b756539bbfa1.png)

can you tell me how can I see the kvm resource usage

**Comment by mhorne484** [comment]
Hi, Installed your template and I have zero items, no triggers. I'm running Zabbix 3.0, should this version be compatible?

**Comment by sramsey822** [comment]
Likewise, linked template to host and came up empty. Did note received error "...Value should be JSON object".  Wondering where the wheels fell off the wagon?

**Comment by bushvin** [comment]
Apologies, the warnings for github seemed to have enden up in my spam box.

This project has only been tested on zabbix 1.8 and 2.0.
I have not used zabbix since.
