### ISSUE TITLE
About automatic discovery

### ISSUE THREAD

**Issue by liuqiqi1** [bushvin/zabbix-kvm-res#5]
hi,Excuse me I am using zabbix version 3.4 Configuring automatic discovery Reporting is not supported,But I use the command line can get the correct output,Have you ever encountered this problem?Or do you have support for version 3.4?look forward to your reply,thanks!

**Comment by bushvin** [comment]
Hi @liuqiqi1 ,
I haven't had the opportunity to immerse myself in Zabbix since v2.0, so I wouldn't know.
I'm sorry I can't be of help.
Maybe @Trikke76 can help out?

**Comment by liuqiqi1** [comment]
> Hi @liuqiqi1 ,
> I haven't had the opportunity to immerse myself in Zabbix since v2.0, so I wouldn't know.
> I'm sorry I can't be of help.
> Maybe @Trikke76 can help out?

thank you  very much

**Comment by Trikke76** [comment]
@liuqiqi1 did you solve your problem ?
normally LLD should still work. not using this implementation myself but imho no changes where made in LLD that would break this is your agent working fine in active / passive

**Comment by liuqiqi1** [comment]
> @liuqiqi1 did you solve your problem ?
> normally LLD should still work. not using this implementation myself but imho no changes where made in LLD that would break this is your agent working fine in active / passive

Thank you for your reply, I plan to install the client into the image, although it looks a bit low, but it is more convenient. Or use ceilometer to transfer data to zabbix to generate images.

**Comment by Trikke76** [comment]
hi,
yes LLD will not work without the agent or something else (like zabbix sender) running the scripts to send data to zabbix
