### ISSUE TITLE
when import the template, report 

### ISSUE THREAD

**Issue by tscswcn** [bushvin/zabbix-kvm-res#6]
Details Import failed
Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "snmpv3_contextname" is missing.

**Comment by Trikke76** [comment]
what is your zabbix version ?

**Comment by tscswcn** [comment]
zabbix V5

**Comment by bushvin** [comment]
Not quite there yet...
I'm looking at updating it for v4.x
