### ISSUE TITLE
global name 'kvm' is not defined line 119 of bin/zabbix-libvirt-res.py

### ISSUE THREAD

**Issue by frspackager** [bushvin/zabbix-kvm-res#9]
should line 119 be referring to **host.conn** instead of kvm.conn?

**/usr/local/bin/zabbix-libvirt-res.py --resource host --action version**
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-libvirt-res.py", line 301, in <module>
    main()
  File "/usr/local/bin/zabbix-libvirt-res.py", line **119**, in main
    is_none(kvm.conn,"Could not connect to KVM using '%s'." % args.uri, 2)
NameError: **_global name 'kvm' is not defined_**

**Comment by bushvin** [comment]
SHould be fixed. Thanks for raising this.

**Comment by frspackager** [comment]
My pleasure. Thanks for the code, all good now.
